import numpy as np
from scipy.constants import mu_0, pi

from src.fields import VectorField

import time
import warnings


class BiotSavartEquationSolver:
    """
    A Biot–Savart law solver used to compute the resultant magnetic field B in 2D-space generated by a constant current
    field I (for example due to wires).
    """

    def solve(self, electric_current: VectorField) -> VectorField:
        """
        Solve the Biot–Savart equation to compute the magnetic field given an electric current field.

        Parameters
        ----------
        electric_current : VectorField
            A vector field I : ℝ² → ℝ³ ; (x, y) → (I_x(x, y), I_y(x, y), I_z(x, y)), where I_x(x, y), I_y(x, y) and
            I_z(x, y) are the 3 components of the electric current vector at a given point (x, y) in space. Note that
            I_z = 0 is always True in our 2D world.

        Returns
        -------
        magnetic_field : VectorField
            A vector field B : ℝ² → ℝ³ ; (x, y) → (B_x(x, y), B_y(x, y), B_z(x, y)), where B_x(x, y), B_y(x, y) and
            B_z(x, y) are the 3 components of the magnetic vector at a given point (x, y) in space. Note that
            B_x = B_y = 0 is always True in our 2D world.
        """

        u0 = 1e-7 # u0/4pi
        n, m, _ = electric_current.shape

        magnetic_field = np.zeros(electric_current.shape)

        indices_ii, indices_jj, indices_k, indices_l = np.indices((n, m, n, m))

        r = np.stack([-indices_k+indices_ii, -indices_l+indices_jj, np.zeros((n, m, n, m))], axis=4)
        rnorm = np.sqrt(np.sum(np.square(r), axis=4))

        with warnings.catch_warnings(): # Pour pas que Numpy nous fasse chier avec ses RuntimeWarning
            warnings.simplefilter("ignore")
            rhat = r/rnorm[:, :, :, :, None]
            bmatrix = np.cross(electric_current[None, None, :, :], rhat, axis=4)/np.square(rnorm)[:, :, :, :, None]

        bmatrix[np.isnan(bmatrix)] = 0
        magnetic_field = np.sum(bmatrix, axis=(2, 3))*u0

        return VectorField(magnetic_field)
